name: Issue Created
on:
  issues:
    types: opened
jobs:
  logIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Log Issue Detaols
        run: |
          echo "Title: ${{ github.event.issue.title }}"
          echo "Body: ${{ github.event.issue.body }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Author: ${{ github.event.issue.user.login }}"