name: Lint, Test & Deploy
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm --prefix "./assignments/assignment-01" ci
      - name: Run Lint Script
        run: npm --prefix "./assignments/assignment-01" run lint
  Test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Node
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install Dependencies
          run: npm --prefix "./assignments/assignment-01" ci
        - name: Run Tests
          run: npm --prefix "./assignments/assignment-01" run test
  Deploy:
    runs-on: unbuntu-latest
    needs: [Lint, Test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm --prefix "./assignments/assignment-01" ci
      - name: Build solution
        run: npm --prefix "./assignments/assignment-01" run build
      - name: Deploy to server
        run: echo "Deploying to some server or other"